show pdbs;
ALTER SYSTEM SET PROCESSES=500 SCOPE=SPFILE; 
alter session set container= freepdb1;
create user dify identified by dify DEFAULT TABLESPACE users quota unlimited on users;
grant DB_DEVELOPER_ROLE to dify;

create user difyMeta0142 identified by difyMetal23456 DEFAULT TABLESPACE users quota unlimited on users;
grant DB_DEVELOPER_ROLE to difyMeta0142;

BEGIN
CTX_DDL.CREATE_PREFERENCE('my_chinese_vgram_lexer','CHINESE_VGRAM_LEXER');
END;

/
